# Generated by Django 5.1.7 on 2025-03-10 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pull_request", "Pull Request"),
                            ("push", "Push"),
                            ("issue_comment", "Issue Comment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                ("repository", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
