# Generated by Django 5.1.7 on 2025-03-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GitHubWebhook',
            new_name='GitHubWebhookEvent',
        ),
    ]
