# Generated by Django 5.1.7 on 2025-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0002_rename_githubwebhook_githubwebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubwebhookevent",
            name="id",
            field=models.UUIDField(
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Delivery ID",
            ),
        ),
    ]
