"""initial_schema

Revision ID: 0be7e58777c1
Revises:
Create Date: 2025-04-11 13:19:57.836587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0be7e58777c1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhookevent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Enum("GITHUB", name="webhooksource"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("repository", sa.String(length=255), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhookevent_actor"), "webhookevent", ["actor"], unique=False
    )
    op.create_index(op.f("ix_webhookevent_id"), "webhookevent", ["id"], unique=False)
    op.create_index(
        op.f("ix_webhookevent_processed"), "webhookevent", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_webhookevent_received_at"),
        "webhookevent",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhookevent_repository"), "webhookevent", ["repository"], unique=False
    )
    op.create_index(
        op.f("ix_webhookevent_source"), "webhookevent", ["source"], unique=False
    )
    op.create_table(
        "pipeline",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETE",
                "FAILED",
                "CANCELLED",
                "PUBLISHED",
                name="pipelinestatus",
            ),
            nullable=False,
        ),
        sa.Column("app_id", sa.String(length=255), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column(
            "triggered_by",
            sa.Enum("WEBHOOK", "MANUAL", name="pipelinetrigger"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=255), nullable=True),
        sa.Column("provider_data", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("webhook_event_id", sa.UUID(), nullable=True),
        sa.Column("log_url", sa.Text(), nullable=True),
        sa.Column("callback_token", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhookevent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_app_id"), "pipeline", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_created_at"), "pipeline", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_pipeline_id"), "pipeline", ["id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_provider"), "pipeline", ["provider"], unique=False
    )
    op.create_index(op.f("ix_pipeline_status"), "pipeline", ["status"], unique=False)
    op.create_index(
        op.f("ix_pipeline_triggered_by"), "pipeline", ["triggered_by"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_webhook_event_id"),
        "pipeline",
        ["webhook_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_webhook_event_id"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_triggered_by"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_status"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_provider"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_id"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_created_at"), table_name="pipeline")
    op.drop_index(op.f("ix_pipeline_app_id"), table_name="pipeline")
    op.drop_table("pipeline")
    op.drop_index(op.f("ix_webhookevent_source"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_repository"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_received_at"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_processed"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_id"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_actor"), table_name="webhookevent")
    op.drop_table("webhookevent")
    # ### end Alembic commands ###
