"""add_job_table

Revision ID: 192d212c87d1
Revises: d9169ab82b46
Create Date: 2025-04-08 12:20:42.664734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "192d212c87d1"
down_revision: Union[str, None] = "d9169ab82b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETE",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("job_type", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("provider_data", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_created_at"), "job", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_id"), "job", ["id"], unique=False)
    op.create_index(op.f("ix_job_job_type"), "job", ["job_type"], unique=False)
    op.create_index(op.f("ix_job_pipeline_id"), "job", ["pipeline_id"], unique=False)
    op.create_index(op.f("ix_job_position"), "job", ["position"], unique=False)
    op.create_index(op.f("ix_job_provider"), "job", ["provider"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)

    if op.get_context().dialect.name == "postgresql":
        op.alter_column(
            "pipeline",
            "id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        op.alter_column(
            "pipeline",
            "webhook_event_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )
        op.alter_column(
            "webhookevent",
            "id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )

    op.create_index(
        op.f("ix_webhookevent_received_at"),
        "webhookevent",
        ["received_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhookevent_received_at"), table_name="webhookevent")

    if op.get_context().dialect.name == "postgresql":
        op.alter_column(
            "webhookevent",
            "id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        op.alter_column(
            "pipeline",
            "webhook_event_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        op.alter_column(
            "pipeline",
            "id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_provider"), table_name="job")
    op.drop_index(op.f("ix_job_position"), table_name="job")
    op.drop_index(op.f("ix_job_pipeline_id"), table_name="job")
    op.drop_index(op.f("ix_job_job_type"), table_name="job")
    op.drop_index(op.f("ix_job_id"), table_name="job")
    op.drop_index(op.f("ix_job_created_at"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
