"""create webhookevent table (sqlalchemy)

Revision ID: b757861a95c5
Revises:
Create Date: 2025-04-07 12:00:19.056587

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import Text, JSON
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b757861a95c5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    inspector = inspect(conn)
    dialect = inspector.dialect.name

    json_type = (
        postgresql.JSONB(astext_type=Text()) if dialect == "postgresql" else JSON()
    )

    op.create_table(
        "webhookevent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "source", sa.Enum("GITHUB", name="webhooksource_enum"), nullable=False
        ),
        sa.Column("payload", json_type, nullable=False),
        sa.Column("repository", sa.String(255), nullable=False),
        sa.Column("actor", sa.String(255), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhookevent_actor"), "webhookevent", ["actor"], unique=False
    )
    op.create_index(op.f("ix_webhookevent_id"), "webhookevent", ["id"], unique=False)
    op.create_index(
        op.f("ix_webhookevent_processed"), "webhookevent", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_webhookevent_repository"), "webhookevent", ["repository"], unique=False
    )
    op.create_index(
        op.f("ix_webhookevent_source"), "webhookevent", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhookevent_source"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_repository"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_processed"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_id"), table_name="webhookevent")
    op.drop_index(op.f("ix_webhookevent_actor"), table_name="webhookevent")
    op.drop_table("webhookevent")
    # ### end Alembic commands ###
