"""Rename build_url to build_id on Pipeline

Revision ID: ca4c8c37fa88
Revises: remove_repo_field
Create Date: 2025-04-22 07:02:09.301806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca4c8c37fa88"
down_revision: Union[str, None] = "remove_repo_field"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pipeline",
        "build_url",
        new_column_name="build_id",
        existing_type=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pipeline",
        "build_id",
        new_column_name="build_url",
        existing_type=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###
