"""add_triggered_by_to_pipeline

Revision ID: d582c098ac1e
Revises: 192d212c87d1
Create Date: 2025-04-08 12:36:06.461783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d582c098ac1e"
down_revision: Union[str, None] = "192d212c87d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "postgresql":
        op.alter_column(
            "job",
            "id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        op.alter_column(
            "job",
            "pipeline_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        op.alter_column(
            "pipeline",
            "id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        op.alter_column(
            "pipeline",
            "webhook_event_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )
        op.alter_column(
            "webhookevent",
            "id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )

    op.add_column(
        "pipeline",
        sa.Column(
            "triggered_by",
            sa.Enum("WEBHOOK", "MANUAL", name="pipelinetrigger"),
            nullable=False,
            server_default="WEBHOOK",
        ),
    )
    op.create_index(
        op.f("ix_pipeline_triggered_by"), "pipeline", ["triggered_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_triggered_by"), table_name="pipeline")
    op.drop_column("pipeline", "triggered_by")

    if op.get_context().dialect.name == "postgresql":
        op.alter_column(
            "webhookevent",
            "id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        op.alter_column(
            "pipeline",
            "webhook_event_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        op.alter_column(
            "pipeline",
            "id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        op.alter_column(
            "job",
            "pipeline_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        op.alter_column(
            "job",
            "id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
