# Generated by Django 5.1.7 on 2025-03-26 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., GitHub Actions, GitLab CI",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "External Provider",
                "verbose_name_plural": "External Providers",
            },
        ),
        migrations.CreateModel(
            name="PipelineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pipeline Template",
                "verbose_name_plural": "Pipeline Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "provider_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration (e.g., {'workflow': 'ci.yml', 'job_id': 'build'})",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which other jobs in this template must succeed before this one starts?",
                        related_name="required_by",
                        to="pipelines.jobtemplate",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_templates",
                        to="pipelines.externalprovider",
                    ),
                ),
                (
                    "pipeline_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_templates",
                        to="pipelines.pipelinetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Template",
                "verbose_name_plural": "Job Templates",
                "ordering": ["pipeline_template", "name"],
                "unique_together": {("pipeline_template", "name")},
            },
        ),
        migrations.CreateModel(
            name="PipelineInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="pipelines.pipelinetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Instance",
                "verbose_name_plural": "Pipeline Instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "callback_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("execution_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict, null=True)),
                ("logs_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="pipelines.jobtemplate",
                    ),
                ),
                (
                    "pipeline_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_instances",
                        to="pipelines.pipelineinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Instance",
                "verbose_name_plural": "Job Instances",
                "ordering": ["pipeline_instance", "created_at"],
                "unique_together": {("pipeline_instance", "job_template")},
            },
        ),
    ]
