# Generated by Django 5.1.7 on 2025-03-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., GitHub Actions, GitLab CI",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        help_text="Type of provider (arbitrary name)", max_length=100
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for API calls (leave empty for default)",
                        max_length=255,
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Credentials data in JSON format (tokens, keys, etc.)",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific settings and configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AlterField(
            model_name="jobtemplate",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_templates",
                to="pipelines.provider",
            ),
        ),
        migrations.DeleteModel(
            name="ExternalProvider",
        ),
    ]
