# Generated by Django 5.1.7 on 2025-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0003_alter_pipelinetemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PUBLISHED", "Published"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
